---
loadbalancer_public_ip : A.B.C.D
controller_private_ips_list : 10.240.0.10,10.240.0.11,10.240.0.12
k8s_internal_virtual_ip: X.X.X.X
# k8s_cluster_cidr: "10.200.0.0/16" 
# k8s_cluster_name: "cloud-native-azure"
# encryption_key:
# controller_0_ip:
# controller_1_ip:
# controller_2_ip: 