---
version: '2'
services:
  nats:
    image: nats:2.2
    hostname: nats-single-js
    container_name: nats-single-js
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: "-c /etc/nats/nats.conf"
    volumes:
      - ./single-config/:/etc/nats
      - ./tmp:/tmp
