---
- hosts: localhost
  become: yes
  tasks:
  - name: Install NATS Server
    apt:
        deb: https://github.com/nats-io/nats-server/releases/download/v2.2.2/nats-server-v2.2.2-amd64.deb
  - name: Install NATS CLI
    apt:
        deb: https://github.com/nats-io/natscli/releases/download/0.0.23/nats-0.0.23-amd64.deb

