---
loadbalancer_public_ip: 52.1.1.1
k8s_cluster_cidr: 10.200.0.0/16
k8s_cluster_name: "cloud-native-azure"
pod_cidr_worker0: 10.200.0.0/24
pod_cidr_worker1: 10.200.1.0/24
pod_cidr_worker2: 10.200.2.0/24