


http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""

rate_limit_resources:
  - label: "natsmonitor"
    local:
      count: 1 
      interval: 1s

input:
  label: ""
  http_client:
    url: http://192.168.2.238:8222/varz
    verb: GET
    headers:
      Content-Type: application/octet-stream
    rate_limit: "natsmonitor"
    timeout: 5s
    payload: ""
    stream:
      enabled: false
      reconnect: true
      codec: lines

buffer:
  none: {}
pipeline:
  threads: 1
  processors: []
output:
  label: ""
  nats:
    urls:
      - nats://192.168.2.247:4222
    subject: benthos.varz

logger:
  level: INFO
  format: json
  add_timestamp: true
  static_fields:
    '@service': benthos
metrics:
  http_server:
    prefix: benthos
    path_mapping: ""
tracer:
  none: {}
shutdown_timeout: 20s
